### ISSUE TITLE
websocket._exceptions.WebSocketConnectionClosedException: socket is already closed.

### ISSUE THREAD

**Issue by vinydl** [n1nj4z33/iqoptionapi#36]
I am getting websocket error frequestnly. What is the solution? How to disconnect API? 

Traceback (most recent call last):
  File "D:\Users\vinayaka.d\Desktop\Python projects\iqoption.py", line 12, in <module>
    api.connect()
  File "C:\Python34\lib\site-packages\iqoptionapi-0.5-py3.4.egg\iqoptionapi\api.py", line 288, in connect
    self.ssid(ssid) # pylint: disable=not-callable
  File "C:\Python34\lib\site-packages\iqoptionapi-0.5-py3.4.egg\iqoptionapi\ws\chanels\ssid.py", line 17, in __call__
    self.send_websocket_request(self.name, ssid)
  File "C:\Python34\lib\site-packages\iqoptionapi-0.5-py3.4.egg\iqoptionapi\ws\chanels\base.py", line 23, in send_websocket_request
    return self.api.send_websocket_request(name, msg)
  File "C:\Python34\lib\site-packages\iqoptionapi-0.5-py3.4.egg\iqoptionapi\api.py", line 123, in send_websocket_request
    self.websocket.send(data)
  File "C:\Python34\lib\site-packages\websocket\_app.py", line 118, in send
    if not self.sock or self.sock.send(data, opcode) == 0:
  File "C:\Python34\lib\site-packages\websocket\_core.py", line 234, in send
    return self.send_frame(frame)
  File "C:\Python34\lib\site-packages\websocket\_core.py", line 259, in send_frame
    l = self._send(data)
  File "C:\Python34\lib\site-packages\websocket\_core.py", line 423, in _send
    return send(self.sock, data)
  File "C:\Python34\lib\site-packages\websocket\_socket.py", line 113, in send
    raise WebSocketConnectionClosedException("socket is already closed.")
websocket._exceptions.WebSocketConnectionClosedException: socket is already closed.

**Comment by vinydl** [comment]
it might be because of internet speed. but however exception should be handled in API
