### ISSUE TITLE
api.getcandles returns None

### ISSUE THREAD

**Issue by adamovivan** [n1nj4z33/iqoptionapi#79]
Hello, please help, here is my code:

import time
from iqoptionapi.api import IQOptionAPI

if __name__ == '__main__':

    api = IQOptionAPI("iqoption.com", "MyUsername", "MyPassword")
    api.connect()
    time.sleep(1)
    api.setactives([1, 2])

    api.getcandles(1, 60, 25)
    time.sleep(1)
    data = api.candles.candles_data
    print(data)
---------------------------------------------------
But it prints "None". Where is my mistake?

**Comment by remarco** [comment]
`from iqoptionapi.api import IQOptionAPI
import datetime
import time
import logging
#logging.basicConfig(format='%(asctime)s %(message)s')

api = IQOptionAPI("iqoption.com", "uname", "pass")

api.connect()
time.sleep(0.5)
print 'Your current blance is: {:.2f}'.format(api.profile.balance)

#How to get candles data: 1st param is the asset or so
#second is the interval size of the candles (currently 60 secs)
#and the third one is the amount of candles we would like to have
api.getcandles(1, 60)
#somehow we need that wait. Don't ask me why. Otherwise we have no data
time.sleep(0.25)
data = api.candles.candles_data
for candles in data:
    st = datetime.datetime.fromtimestamp(candles[0]+60).strftime('%Y-%m-%d %H:%M:%S')
    '''
    candles data
    0th entry: timestamp of candle
    1st entry: where candles starts in the interval
    2nd entry: where candles finishes in the interval
    3rd entry: upper wick
    4th entry: lower wick
    '''
    print st, candles


time.sleep(0.5)`


output is : 
Your current blance is: 212705.28
2018-02-16 10:03:00 [1518768120, 1253265, 1253140, 1253265, 1252900]
2018-02-16 10:04:00 [1518768180, 1253140, 0, 1253175, 1252820]

if api.getcandles(1, 60, 25)
output is : 
Traceback (most recent call last):
  File "C:\Users\bot_data.py", line 16, in <module>
    api.getcandles(1, 60, 25)
TypeError: __call__() takes exactly 3 arguments (4 given)

i dont know where 4 arguments found :(

**Comment by gwdm** [comment]
You put this comment in your script:
"somehow we need that wait. Don't ask me why. Otherwise we have no data"
getcandles just sends a web socket message it does not wait for a response. Your code needs to handle that. Putting a time.sleep in your code may not always work it would be better to wait for the return message. This is obviously true of all web socket requests that require a response.

**Comment by remarco** [comment]
this is no my code. it is from example... loot at readme.
4th argument must not be self...
look at this code:
https://github.com/n1nj4z33/iqoptionapi/blob/master/iqoptionapi/ws/chanels/candles.py

**Comment by remarco** [comment]
it solved reinstalling manualy.

**Comment by elmschaym** [comment]
i got the same problem until now i didn't find ways to solve this problem.. @remarco what do you mean for reinstalling manually, i did that also

**Comment by remarco** [comment]
download zip from git and install... check if you have file in iqoptionapi/ws/objects/listinfodata.py
if you have all must work. if not you installed with command pip install iqoptionapi. i dont know how git work but last changes not in package... N1nj4z33 ?! please solve this !!!

**Comment by remarco** [comment]
from iqoptionapi.api import IQOptionAPI
import datetime
import time
import logging
#logging.basicConfig(format='%(asctime)s %(message)s')

api = IQOptionAPI("iqoption.com", "uname", "pass")

api.connect()
time.sleep(0.5)
print 'Your current blance is: {:.2f}'.format(api.profile.balance)
api.getcandles(1, 60, 25)
#somehow we need that wait. Don't ask me why. Otherwise we have no data
time.sleep(0.25)
data = api.candles.candles_data
for candles in data:
    st = datetime.datetime.fromtimestamp(candles[0]+60).strftime('%Y-%m-%d %H:%M:%S')
    print st, candles

OUTPUT IS:
Your current blance is: 203584.95
2018-03-12 21:30:00 [1520882940, 1233520, 1233520, 1233530, 1233510]
2018-03-12 21:31:00 [1520883000, 1233520, 1233580, 1233580, 1233515]
2018-03-12 21:32:00 [1520883060, 1233580, 1233755, 1233755, 1233580]
2018-03-12 21:33:00 [1520883120, 1233755, 1233755, 1233790, 1233750]
2018-03-12 21:34:00 [1520883180, 1233755, 1233740, 1233770, 1233710]
2018-03-12 21:35:00 [1520883240, 1233740, 1233640, 1233750, 1233640]
2018-03-12 21:36:00 [1520883300, 1233640, 1233645, 1233645, 1233530]
2018-03-12 21:37:00 [1520883360, 1233645, 1233635, 1233645, 1233600]
2018-03-12 21:38:00 [1520883420, 1233635, 1233605, 1233685, 1233605]
2018-03-12 21:39:00 [1520883480, 1233605, 1233565, 1233610, 1233550]
2018-03-12 21:40:00 [1520883540, 1233565, 1233505, 1233570, 1233480]
2018-03-12 21:41:00 [1520883600, 1233505, 1233385, 1233505, 1233290]
2018-03-12 21:42:00 [1520883660, 1233385, 1233380, 1233410, 1233290]
2018-03-12 21:43:00 [1520883720, 1233380, 1233350, 1233385, 1233295]
2018-03-12 21:44:00 [1520883780, 1233350, 1233440, 1233450, 1233350]
2018-03-12 21:45:00 [1520883840, 1233440, 1233390, 1233440, 1233335]
2018-03-12 21:46:00 [1520883900, 1233390, 1233400, 1233440, 1233390]
2018-03-12 21:47:00 [1520883960, 1233400, 1233400, 1233400, 1233390]
2018-03-12 21:48:00 [1520884020, 1233400, 1233405, 1233405, 1233395]
2018-03-12 21:49:00 [1520884080, 1233405, 1233400, 1233460, 1233390]
2018-03-12 21:50:00 [1520884140, 1233400, 1233455, 1233480, 1233380]
2018-03-12 21:51:00 [1520884200, 1233455, 1233490, 1233490, 1233450]
2018-03-12 21:52:00 [1520884260, 1233490, 1233560, 1233560, 1233490]
2018-03-12 21:53:00 [1520884320, 1233560, 1233550, 1233585, 1233550]
2018-03-12 21:54:00 [1520884380, 1233550, 0, 1233590, 1233550]
>>> 
if you cant get data incrase time.sleep to time.sleep(2) 
if your internet not so fast.

**Comment by leonardoRampazzo** [comment]
api = IQOptionAPI("iqoption.com", "MyUsername", "MyPassword")
api.connect()
time.sleep(1)
api.setactives([1, 2])

api.getcandles(1, 60, 25)
time.sleep(1)
data = api.candles.candles_data
print(data)

what I see in here, by the way u are printing. u are using python3, and the api was write in python2.

**Comment by remarco** [comment]
Microsoft Windows [Version 10.0.16299.248]
(c) 2017 Microsoft Corporation.
C:\Users\user>python -V
**Python 2.7.14**
C:\Users\user>

**Comment by adamovivan** [comment]
leonardoRampazzo, I tried with python 2.7, but it still doesn't work.

**Comment by remarco** [comment]
ahaa!!! i tray your code. only when print none if you use wrong login or pass...

api = IQOptionAPI("iqoption.com", "aa", "aa")
api.connect()
time.sleep(1)
api.getcandles(6, 60, 5)
time.sleep(1)
data = api.candles.candles_data
print data
output is:
File "C:\Python27\lib\site-packages\websocket\_app.py", line 269, in _callback
    callback(self, *args)
  File "C:\Python27\lib\site-packages\iqoptionapi-0.5-py2.7.egg\iqoptionapi\ws\client.py", line 33, in on_message
    self.api.profile.balance = message["msg"]["balance"]
None
>>> 
with right login pass 
[[1521041400, 106242500, 106212500, 106242500, 106212500], [1521041460, 106212500, 106193500, 106212500, 106190500], [1521041520, 106193500, 106215000, 106218500, 106191500], [1521041580, 106215000, 106210000, 106226000, 106208500], [1521041640, 106210000, 0, 106216000, 106206000]]
>>> 

**double check your login and pass**
are you have iqoption accaunt???

**Comment by adamovivan** [comment]
@remarco I reinstalled api and it works now. Thanks :)

**Comment by nguyencse** [comment]
I have logged in successfully, but when I get candles by command api.getcandles(1, 60, 25), it's alway return None. How can I fix it? Thanks everyone :(
